[package]
name = "python"
edition = "2021"
resolver = "2"

[lib]
name = "neuromorphic_drivers"
crate-type = ["cdylib"]

[dependencies]
neuromorphic-drivers = {path = "../drivers"}
numpy = "0.25.0"
paste = "1.0"
pyo3 = {version = "0.25.1", features = ["extension-module"]}

[build-dependencies]
cc = "1.0"
neuromorphic-drivers = {path = "../drivers"}
paste = "1.0"
reflect = {path = "../reflect"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde-generate = "0.29.0"
toml = {version = "0.8", features = ["parse"]}
